t_basefile:
	g++ -o t_basefile tests/t_basefile.cpp basefile.cpp ../lab1/src/my_string.cpp

t_base32file:
	g++ -o t_base32file tests/t_base32file.cpp basefile.cpp ../lab1/src/my_string.cpp

t_rlefile:
	g++ -o t_rlefile tests/t_rlefile.cpp basefile.cpp ../lab1/src/my_string.cpp

t_base32file2:
	g++ -o t_base32file2 tests/t_base32file2.cpp basefile.cpp ../lab1/src/my_string.cpp

t_rlefile2:
	g++ -o t_rlefile2 tests/t_rlefile2.cpp basefile.cpp ../lab1/src/my_string.cpp

t_basefile2:
	g++ -o t_basefile2 tests/t_basefile2.cpp basefile.cpp ../lab1/src/my_string.cpp


test:
	./t_basefile
	./t_base32file
	./t_rlefile
	./t_base32file2
	./t_rlefile2

clean:
	rm -f t_basefile t_base32file t_rlefile t_base32file2 t_rlefile2
