name: CMake CI/CD Pipeline

on:
  push:
    branches: [dev]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Debug - list files
        run: |
          pwd
          ls -la
          ls -la labs/data-str/ || echo "Папка labs/data-str не найдена"


